"""add user and webhook tables

Revision ID: 0f4c2e503074
Revises: 3b96216d52cb
Create Date: 2026-03-26 09:05:46.517122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f4c2e503074'
down_revision: Union[str, Sequence[str], None] = '3b96216d52cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhooks_id'), ['id'], unique=False)

    with op.batch_alter_table('marksheets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_marksheets_file_hash'), ['file_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marksheets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marksheets_file_hash'))
        batch_op.drop_column('file_hash')

    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhooks_id'))

    op.drop_table('webhooks')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
