"""initial schema

Revision ID: 3b96216d52cb
Revises: 
Create Date: 2026-03-26 05:26:15.669927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b96216d52cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('pattern_hints', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boards_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_boards_id'), ['id'], unique=False)

    op.create_table('standard_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('standard_subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_standard_subjects_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_standard_subjects_id'), ['id'], unique=False)

    op.create_table('upload_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=True),
    sa.Column('processed_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upload_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_batches_id'), ['id'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('roll_number', sa.String(length=50), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('exam_year', sa.Integer(), nullable=True),
    sa.Column('exam_type', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('school_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roll_number', 'board_id', 'exam_year', name='uq_student_roll_board_year')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_roll_number'), ['roll_number'], unique=False)

    op.create_table('subject_mapping_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.String(length=200), nullable=False),
    sa.Column('standard_subject_id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.Integer(), nullable=True),
    sa.Column('confidence_threshold', sa.Float(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['standard_subject_id'], ['standard_subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subject_mapping_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subject_mapping_rules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subject_mapping_rules_raw_text'), ['raw_text'], unique=False)

    op.create_table('marksheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('raw_ocr_text', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('board_detected_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['upload_batches.id'], ),
    sa.ForeignKeyConstraint(['board_detected_id'], ['boards.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marksheets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marksheets_id'), ['id'], unique=False)

    op.create_table('marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marksheet_id', sa.Integer(), nullable=False),
    sa.Column('raw_subject_name', sa.String(length=200), nullable=False),
    sa.Column('standard_subject_id', sa.Integer(), nullable=True),
    sa.Column('mapping_confidence', sa.Float(), nullable=True),
    sa.Column('marks_obtained', sa.Float(), nullable=True),
    sa.Column('max_marks', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['marksheet_id'], ['marksheets.id'], ),
    sa.ForeignKeyConstraint(['standard_subject_id'], ['standard_subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marks_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marks_id'))

    op.drop_table('marks')
    with op.batch_alter_table('marksheets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marksheets_id'))

    op.drop_table('marksheets')
    with op.batch_alter_table('subject_mapping_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subject_mapping_rules_raw_text'))
        batch_op.drop_index(batch_op.f('ix_subject_mapping_rules_id'))

    op.drop_table('subject_mapping_rules')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_roll_number'))
        batch_op.drop_index(batch_op.f('ix_students_id'))

    op.drop_table('students')
    with op.batch_alter_table('upload_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_batches_id'))

    op.drop_table('upload_batches')
    with op.batch_alter_table('standard_subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_standard_subjects_id'))
        batch_op.drop_index(batch_op.f('ix_standard_subjects_code'))

    op.drop_table('standard_subjects')
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boards_id'))
        batch_op.drop_index(batch_op.f('ix_boards_code'))

    op.drop_table('boards')
    # ### end Alembic commands ###
